### ISSUE TITLE
How to fix CI failed caused by code style issue

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#102]
Take a look at the latest build and found that CI failed at the `golint` and `goimports` checking.

Here is the `golint` output:
```
### golint
ir/enum/enum.go:70:2: don't use underscores in Go names; const CallingConvARM_APCS should be CallingConvARMAPCS
ir/enum/enum.go:71:2: don't use underscores in Go names; const CallingConvARM_AAPCS should be CallingConvARMAAPCS
ir/enum/enum.go:72:2: don't use underscores in Go names; const CallingConvARM_AAPCS_VFP should be CallingConvARMAAPCSVFP
ir/enum/enum.go:80:2: don't use underscores in Go names; const CallingConvIntelOCL_BI should be CallingConvIntelOCLBI
ir/enum/enum.go:85:2: don't use underscores in Go names; const CallingConvHHVM_C should be CallingConvHHVMC
ir/enum/enum.go:90:2: don't use underscores in Go names; const CallingConvAMDGPU_VS should be CallingConvAMDGPUVS
ir/enum/enum.go:91:2: don't use underscores in Go names; const CallingConvAMDGPU_GS should be CallingConvAMDGPUGS
ir/enum/enum.go:92:2: don't use underscores in Go names; const CallingConvAMDGPU_PS should be CallingConvAMDGPUPS
ir/enum/enum.go:93:2: don't use underscores in Go names; const CallingConvAMDGPU_CS should be CallingConvAMDGPUCS
ir/enum/enum.go:96:2: don't use underscores in Go names; const CallingConvAMDGPU_HS should be CallingConvAMDGPUHS
ir/enum/enum.go:98:2: don't use underscores in Go names; const CallingConvAMDGPU_LS should be CallingConvAMDGPULS
ir/enum/enum.go:99:2: don't use underscores in Go names; const CallingConvAMDGPU_ES should be CallingConvAMDGPUES
ir/metadata/metadata.go:195:6: type name will be used as metadata.MetadataID by other packages, and that stutters; consider calling this ID
ir/types/types.go:32:2: don't use ALL_CAPS in Go names; use CamelCase
ir/types/types.go:34:2: don't use ALL_CAPS in Go names; use CamelCase
ir/types/types.go:384:2: don't use underscores in Go names; const FloatKindX86_FP80 should be FloatKindX86FP80
ir/types/types.go:386:2: don't use underscores in Go names; const FloatKindPPC_FP128 should be FloatKindPPCFP128
```

But some naming suggestions by `golint` are non-sense for me, like: `CallingConvAMDGPUES` would quite confusing. So the problem is how can we fix these warning

- disable whole `golint`(probably not a good idea)
- if could, disable some warning for certain case in `golint`
- fix all naming to fit `golint`

p.s. For me, the second one sounds better.

**Comment by mewmew** [comment]
> But some naming suggestions by golint are non-sense for me, like: CallingConvAMDGPUES would quite confusing. So the problem is how can we fix these warning

Indeed. We went for using Go naming conventions wherever possible, and using `_` to improve readability where it makes sense. In essence a pragmatic rather than dogmatic approach.

So, if there is a "magic" golint comment or something to disable it, either for a few source files/packages/or parts of packages that would be perfect.

@dannypsnl, If you know how to disable specific warnings that would be really lovely. Feel free to submit a PR for this :)

Cheers,
Robin

**Comment by mewmew** [comment]
Having had a quick look at this, I think the way to go is to replace `golint` with `revive`. This lets us exclude specific source files. After thinking a bit I would prefer to avoid adding a lot of "magic" comments to the source code. Lets keep the linting a tools only configuration.

From https://github.com/mgechev/revive:
```bash
revive -config revive.toml -exclude file1.go -exclude file2.go -formatter friendly github.com/mgechev/revive package/...
```

**Comment by mewmew** [comment]
I'll update [ci_checks.sh](https://github.com/mewmew/ci/blob/master/ci_checks.sh) to use `revieve`, then we can add the config to the llir/llvm repo.

**Comment by dannypsnl** [comment]
I would create PR for `.travis.yml` update that installs `revieve`, but doesn't that `ci_checks.sh` should be put in the project?

**Comment by mewmew** [comment]
> I would create PR for .travis.yml update that installs revieve, but doesn't that ci_checks.sh should be put in the project?

I just updated mewmew/ci: https://github.com/mewmew/ci/commit/e5d5b798c410f17f38e52853a74732f491e6323d

**Comment by mewmew** [comment]
We can update `.travis.yml` to use `get_tools.sh` from https://github.com/mewmew/ci/raw/master/get_tools.sh
