### ISSUE TITLE
Generate binary code directly from lib

### ISSUE THREAD

**Issue by Vdimir** [llir/llvm#108]
Currently only producing text representation of llvm IR avaliable.
So, to produce executable or object file external calls of `clang` or `llc` required.
Also it is impossible to produce code and execute it on fly in JIT manner.

**Comment by mewmew** [comment]
Hi @Vdimir!

The intention of `llir/llvm` is to complement LLVM, not to replace it. I agree that it would be really cool to be able to generate code and execute on the fly without having to use the external tools.

However, there are no direct plans on implementing code generation as part of `llir/llvm`.

That being said, it is definitely feasible for anyone to write a `codegen` package that could produce code and optionally execuite it on the fly in JIT manner. This `codegen` package does not have to live in `llir/llvm` but could rather work on the IR of [llir/llvm/ir](https://godoc.org/github.com/llir/llvm/ir), and may live anywhere, including `https://github.com/Vdimir/codegen` ;)

The main focus of `llir/llvm` at this time is to provide a pure Go API for interfacing with LLVM IR. We have input and output pretty much done. Future work will aim to improve upon analysis, starting with improving the data flow analysis API.

Wish you all the best and happy coding!

Cheers,
Robin

**Comment by mewmew** [comment]
I'll close this issue for now. Definitely let us know if you do get started with a `codegen` package @Vdimir!
