### ISSUE TITLE
constant folding

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#113]
This issue tracks support for folding of constant expressions, in particular, the implementation of the `Simplify` method of the [Expression interface](https://godoc.org/github.com/llir/llvm/ir/constant#Expression) which is the canonical way to fold constants in `llir/llvm`.

```go
type Expression interface {
    Constant
    // Simplify returns an equivalent (and potentially simplified) constant to
    // the constant expression.
    Simplify() Constant
}
```

To get the ball rolling, rev 007ec8d5f2edca1d8ca07b8b745c5b3f05c3217e adds support for folding/simplifying `sext` (sign extension) constant expressions.

cc: @pwaller, we finally start to get to the more interesting parts. Optimization of LLVM IR :)

**Comment by mewmew** [comment]
Commit b85ca175725ff59102503c86be2934bd3b9a99d3 was supposed to reference this issue. However, the commit message was:

```
This is so we return a useful value instead of panic'ing until
#113 is resolved.
```

So, `#113` with `#` being at the start of the line was interpreted as a comment and thus stripped from the commit message. Makes me wonder, how often has the issue number prefix `#` been conflated with the line-comment prefix `#` of commit messages throughout the history of open source projects.

**Comment by dannypsnl** [comment]
Do we still have something need to do here?

**Comment by mewmew** [comment]
> Do we still have something need to do here?

Perhaps constant folding is better to implement outside of the core `llir/llvm` API. It was only ever partially implemented for a few constant types, and never supported fully.

I think we can safely remove these methods in their entirety, as their functionality was never implemented enough to be useful for users to rely on.

Then we can move this concept to an `irutil` package.

```go
// Simplify returns an equivalent (and potentially simplified) constant to
// the constant expression.
func Simplify(c constant.Constant) constant.Constant {
}
```

**Comment by mewmew** [comment]
Moved to `irutil` by @dannypsnl in llir/irutil#3.

As discussed in https://github.com/llir/llvm/issues/113#issuecomment-850797736, the functionality of constant folding was never properly implemented so it is very unlikely that users have come to rely on it. For this reason, it will be removed from `llir/llvm/ir/constant` in its entirety. The functionality of constant folding has been moved to `irutil` where it will be developed further.
