### ISSUE TITLE
proposal: consider dual-licensing llir/llvm under public domain and BSD

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#120]
The intention of releasing `llir/llvm` into the public domain has always been to make it as easy as possible for users to use/copy/modify the library without having to worry about satisfying any license requirements.

While there have been no such reports yet, for other public domain libraries, there is at times the issue where users can't use the library simply because it's public domain and does not have a specific license attached to it. See for instance https://github.com/nothings/stb/blob/master/docs/why_public_domain.md

Extract below:

> ```
> However, public domain has frictions of its own, because
> public domain declarations aren't necessary recognized
> in the USA and some other locations. For that reason,
> I recommend a declaration along these lines:
>
> // This software is dual-licensed to the public domain and under the following
> // license: you are granted a perpetual, irrevocable license to copy, modify,
> // publish, and distribute this file as you see fit.
> ```

As such, to anticipate this future issue, I propose we dual-license `llir/llvm` to the public domain and under the same [BSD license as used by the Go distribution](https://golang.org/LICENSE).

I'm open to other suggestions and input on this issue.

Perhaps, we arrive at the conclusion that it would be unnecessary to do so, and we should only consider it after the first users reporting this to be an issue for them adopting `llir/llvm`.

Cheers,
Robin

cc: @pwaller, @dannypsnl

**Comment by mewmew** [comment]
Additional background, one reason to do this is also that [pkg.go.dev](https://pkg.go.dev/) doesn't recognize `UNLICENSED`. I've submitted that issue upstream, but the issue tracker of `pkg.go.dev` is not open to the public so I can't track the progress.

From https://pkg.go.dev/github.com/llir/llvm/ir?tab=overview

>  README not displayed due to license restrictions. See our license policy. 

![screenshot_2019-12-20_17:32:10](https://user-images.githubusercontent.com/1414531/71269061-b20f7480-234e-11ea-87af-7b0cfa94faef.png)

**Comment by mewmew** [comment]
The proposal is therefore to add a BSD-style license alongside the public domain (`UNLICENSE`), and add a notice to the README that `llir/llvm` is dual-licensed to the public domain and under a simplified BSD license.

As such, we would use [2-clause BSD](https://opensource.org/licenses/BSD-2-Clause) (rather than [3-clause BSD](https://opensource.org/licenses/BSD-3-Clause)), both of which are recognized by `pkg.go.dev` and 2-clause imposing less restrictions on the users of `llir/llvm`.

**Comment by pwaller** [comment]
:+1:

**Comment by mewmew** [comment]
> +1

@pwaller, would you review #121 and if it looks right to you, give a +1 in the PR. That way we can track consent for the PR before merge.

**Comment by mewmew** [comment]
Hmm. Turns out that 0-clause BSD is not supported by pkg.go.dev (ref: golang/go#36983). Thus reopening this issue until we figure out what route to take.

For reference, gioui.org which is also dual-licensed into the public domain and MIT works. But that required manual efforts to contact the pkg.go.dev maintainers. ref: golang/go#36840.

**Comment by dannypsnl** [comment]
Just see https://pkg.go.dev/mod/github.com/llir/llvm is available with BSD-0 and Unlicense. @mewmew This means the issue is resolved?

**Comment by mewmew** [comment]
> Just see https://pkg.go.dev/mod/github.com/llir/llvm is available with BSD-0 and Unlicense. @mewmew This means the issue is resolved?

Yes, the issue is now resolved :)
