### ISSUE TITLE
proposal: use notion of "low-entropy" to decide output format of integer literals (decimal vs. hexadecimal)

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#125]
When printing integer literals to LLVM IR assembly format, they may be output in either decimal or hexadecimal format. The idea is to use low-entropy as a metric to decide which encoding to use. To give an example, consider the bitmask `0x80000000`.

The decimal representation of `0x80000000` is `2147483648`.

Lets use a naiive notion of entropy; a histogram of the digits used, and the fewer the bins, the lower the entropy. As such, `0x80000000` has 2 bins (not counting the `0x` prefix), where bin `8` has one member and bin `0` has seven members. Similarly, `2147483648` has seven bins, as illustrated below.

hexadecimal representation requires *two* bins:

```
   bin0: 0 0 0 0 0 0 0   (7 members)
   bin8: 8               (1 member)
```

decimal representation requires *seven* bins:

```
   bin1: 1
   bin2: 2
   bin3: 3
   bin4: 4 4 4
   bin6: 6
   bin7: 7
   bin8: 8 8
```

Thus, hexadecimal notation has lower entropy than decimal notation for the example integer literal. As such, `llir/llvm/ir` would output `u0x80000000`.

Motivating example:

Before:
```llvm
   %t26 = and %uint64 %t25, 9218868437227405312
```

After:
```llvm
   %t26 = and %uint64 %t25, u0x7FF0000000000000
```

Given that:
```
9218868437227405312
= 0x7FF0000000000000
```

**Comment by dannypsnl** [comment]
> When printing integer literals to LLVM IR assembly format, they may be output in either decimal or hexadecimal format.

Do you know which part of the code makes this situation? Is that caused by https://github.com/llir/llvm/blob/master/ir/constant/const_int.go#L19 `big.Int`? In this case, I thought probably provide a format function to help users pick the result they want if they don't do this then it seems like the format is not important for them? Not sure, it's still good that has a consistency output.

**Comment by mewmew** [comment]
> When printing integer literals to LLVM IR assembly format, they may be output in either decimal or hexadecimal format.

To clarify. Currently, they are always printed in decimal format (using `c.X.String()` of the `*big.Int`).

This proposal suggests to update [line 130](https://github.com/llir/llvm/blob/bf75e23be2528b0ab2e24e6ea0f9f71872398ab7/ir/constant/const_int.go#L130) of `constant.Int.String`, as follows:

Before:
```go
// Ident returns the identifier associated with the constant.
func (c *Int) Ident() string {
	// ...
	return c.X.String()
}
```

After:
```go
// Ident returns the identifier associated with the constant.
func (c *Int) Ident() string {
	// ...
	if decimalEntropy(c.X) > hexEntropy(c.X) {
		return "u0x" + c.X.Text(16)
	}
	return c.X.String()
}
```

> Not sure, it's still good that has a consistency output.

I agree, consistent output is important. For floating-point numbers, we always output the floating-point literal (e.g. `2.125`) if it is an exact representation of the floating-point value. However, output using floating-point literal notation is not extract, we output as a hexadecimal floating-point literal to avoid precision loss. So, while the output doesn't always look the same, there is a *simple* rule which makes the output consistent if the users knows the rule.

Similarly, this proposal introduces the "rule" of low-entropy output for integer literals. The output would always be exact as neither the decimal nor the hexadecimal notation of integer values have precision loss. The main idea is to make the output more readable in the general case, as illustrated by:

```llvm
   %t26 = and %uint64 %t25, 9218868437227405312
```

vs.

```llvm
   %t26 = and %uint64 %t25, u0x7FF0000000000000
```

Personally, I'd prefer to not add too many *knobs* for configuring the output representation, but rather arrive at a default representation that is used throughout. As such, I propose we stay away from adding custom formatters configurable by the user. Mainly as there are so many aspects of the output which could be configured, and giving custom formatters for all of them would pollute the API.

Well, this is still food for thought.

I'm fine either way. The benefit of implementing this proposal is that the output may be more readable at times. The benefit of keeping things as is is that there is less surprise in the output representation. Both have merit, so require some thought.

Cheers,
Robin

**Comment by pwaller** [comment]
SGTM!

**Comment by mewmew** [comment]
To see examples of how the output of integer literals have been updated by PR #126, see https://github.com/llir/testdata/pull/1/files

<details><summary>Detailed example calculations of hex and decimal entropy used as basis to determine and fine-tune `minEntropyDiff` and `maxHexEntropy`</summary>
<pre>
# Print as hex:

(unique hex digits: 1) hex: (length=4) 0x1111 | dec: 4369 (length=4) | hex entropy: 0.25 (max hex entropy: 0.5) | dec entropy: 1 (unique dec digits: 4) |    ---> print as hex: 0x1111
(unique hex digits: 1) hex: (length=4) 0xffff | dec: 65535 (length=5) | hex entropy: 0.25 (max hex entropy: 0.5) | dec entropy: 0.6 (unique dec digits: 3) |    ---> print as hex: 0xffff
(unique hex digits: 1) hex: (length=6) 0xffffff | dec: 16777215 (length=8) | hex entropy: 0.16666666666666666 (max hex entropy: 0.3333333333333333) | dec entropy: 0.625 (unique dec digits: 5) |    ---> print as hex: 0xffffff
(unique hex digits: 1) hex: (length=7) 0xccccccc | dec: 214748364 (length=9) | hex entropy: 0.14285714285714285 (max hex entropy: 0.42857142857142855) | dec entropy: 0.7777777777777778 (unique dec digits: 7) |    ---> print as hex: 0xccccccc
(unique hex digits: 1) hex: (length=7) 0xfffffff | dec: 268435455 (length=9) | hex entropy: 0.14285714285714285 (max hex entropy: 0.42857142857142855) | dec entropy: 0.6666666666666666 (unique dec digits: 6) |    ---> print as hex: 0xfffffff
(unique hex digits: 1) hex: (length=8) 0xffffffff | dec: 4294967295 (length=10) | hex entropy: 0.125 (max hex entropy: 0.375) | dec entropy: 0.6 (unique dec digits: 6) |    ---> print as hex: 0xffffffff
(unique hex digits: 1) hex: (length=14) 0x55555555555555 | dec: 24019198012642645 (length=17) | hex entropy: 0.07142857142857142 (max hex entropy: 0.35714285714285715) | dec entropy: 0.8 (unique dec digits: 8) |    ---> print as hex: 0x55555555555555
(unique hex digits: 1) hex: (length=14) 0xffffffffffffff | dec: 72057594037927935 (length=17) | hex entropy: 0.07142857142857142 (max hex entropy: 0.35714285714285715) | dec entropy: 0.7 (unique dec digits: 7) |    ---> print as hex: 0xffffffffffffff
(unique hex digits: 1) hex: (length=15) 0x222222222222222 | dec: 153722867280912930 (length=18) | hex entropy: 0.06666666666666667 (max hex entropy: 0.3333333333333333) | dec entropy: 0.9 (unique dec digits: 9) |    ---> print as hex: 0x222222222222222
(unique hex digits: 1) hex: (length=15) 0x333333333333333 | dec: 230584300921369395 (length=18) | hex entropy: 0.06666666666666667 (max hex entropy: 0.3333333333333333) | dec entropy: 0.9 (unique dec digits: 9) |    ---> print as hex: 0x333333333333333
...

# Print as dec:

(unique hex digits: 3) hex: (length=4) 0x1a00 | dec: 6656 (length=4) | hex entropy: 0.75 (max hex entropy: 0.5) | dec entropy: 0.5 (unique dec digits: 2) |    ---> print as dec: 6656
(unique hex digits: 4) hex: (length=4) 0x1a3b | dec: 6715 (length=4) | hex entropy: 1 (max hex entropy: 0.5) | dec entropy: 1 (unique dec digits: 4) |    ---> print as dec: 6715
(unique hex digits: 4) hex: (length=4) 0x1a5b | dec: 6747 (length=4) | hex entropy: 1 (max hex entropy: 0.5) | dec entropy: 0.75 (unique dec digits: 3) |    ---> print as dec: 6747
(unique hex digits: 4) hex: (length=4) 0x1a78 | dec: 6776 (length=4) | hex entropy: 1 (max hex entropy: 0.5) | dec entropy: 0.5 (unique dec digits: 2) |    ---> print as dec: 6776
(unique hex digits: 2) hex: (length=4) 0x1aaa | dec: 6826 (length=4) | hex entropy: 0.5 (max hex entropy: 0.5) | dec entropy: 0.75 (unique dec digits: 3) |    ---> print as dec: 6826
(unique hex digits: 4) hex: (length=4) 0x1acb | dec: 6859 (length=4) | hex entropy: 1 (max hex entropy: 0.5) | dec entropy: 1 (unique dec digits: 4) |    ---> print as dec: 6859
(unique hex digits: 3) hex: (length=4) 0x1acc | dec: 6860 (length=4) | hex entropy: 0.75 (max hex entropy: 0.5) | dec entropy: 0.75 (unique dec digits: 3) |    ---> print as dec: 6860
(unique hex digits: 4) hex: (length=4) 0x1ad3 | dec: 6867 (length=4) | hex entropy: 1 (max hex entropy: 0.5) | dec entropy: 0.75 (unique dec digits: 3) |    ---> print as dec: 6867
(unique hex digits: 3) hex: (length=4) 0x1aff | dec: 6911 (length=4) | hex entropy: 0.75 (max hex entropy: 0.5) | dec entropy: 0.75 (unique dec digits: 3) |    ---> print as dec: 6911
(unique hex digits: 4) hex: (length=4) 0x1b6d | dec: 7021 (length=4) | hex entropy: 1 (max hex entropy: 0.5) | dec entropy: 1 (unique dec digits: 4) |    ---> print as dec: 7021
...
</pre>
</details>
