### ISSUE TITLE
print canonical representation of NaN floating-point float value in double-precision

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#133]
While updating the test cases to LLVM 10.0, a precision loss was noticed during round-trip (parse -> print) of double-precision floating-point values.

In particular, when parsing `double 0x7FF8000000000000` and later printing the floating-point value, the value is printed as `double 0x7FF8000000000001`.

We need to further investigate the cause of this.

The test case that helped highlight the issue was [testdata/llvm/test/Transforms/InstCombine/fma.ll](https://github.com/llir/testdata/blob/master/llvm/test/Transforms/InstCombine/fma.ll).

**Comment by sangisos** [comment]
Is it not only different ways of representing NaN?

From [wikipedia](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#Exponent_encoding):
> The exponents 00016 and 7ff16 have a special meaning:
> 
>     000000000002=00016 is used to represent a signed zero (if F = 0) and subnormals (if F ≠ 0); and
>     111111111112=7ff16 is used to represent ∞ (if F = 0) and NaNs (if F ≠ 0),
> 
> where F is the fractional part of the significand. All bit patterns are valid encoding. 
Or have I missed something?

**Comment by mewmew** [comment]
> Is it not only different ways of representing NaN?

Yeah, I think you are right. The mantissa `F = 0x8000000000000` and `F = 0x8000000000001` both represent NaN (as `F != 0`).

So perhaps what we should look into is to only print the canonical representation of NaN.

From https://anniecherkaev.com/the-secret-life-of-nan:
```
s 11111 1xxxxxxxxxx = quiet     (qNaN)
s 11111 0xxxxxxxxxx = signaling (sNaN) **
        ^
        |
    quiet bit
```

Where `**` denote that at least one of the 'x' bits has to be set, since the mantissa must be non-zero to denote NaN.

**Comment by mewmew** [comment]
Removed the *bug* label, as the output IR is still semantically correct. Having a canonical representation of NaN helps support round-trip encoding/decoding, which is still useful. But, the current implementation is no longer classified as having a bug.

**Comment by dannypsnl** [comment]
maybe not related, but see https://github.com/llir/llvm/blob/master/ir/constant/const_float.go#L198-L213, KindDouble missing set-precision operation. does that ok? @mewmew

**Comment by mewmew** [comment]
Hi @dannypsnl,

Thanks for looking into this. When using `math/big.Float.SetFloat64` and `math/big.NewFloat` both set the precision to 53 (which is the same as `float64` uses). `SetFloat64` changes the precision to 53 if the previous precision was 0, which it was in our case. It could still be worth it to make this code more clear by explicitly setting the precision.

Feel free to try different approaches and see if you managed to get the round-trip test to PASS :) Just remember to enable this test case:

https://github.com/llir/llvm/blob/069ed1206c0642af6dcd37d1fcd86adda77795e5/asm/asm_test.go#L80

```go
		// fsub constant expressions.
		//{path: "../testdata/llvm/test/Transforms/InstCombine/fma.ll"}, // TODO: enable once https://github.com/llir/llvm/issues/133 is resolved.
```

```
$ go doc math/big.SetFloat64
package big // import "math/big"

func NewFloat(x float64) *Float
    NewFloat allocates and returns a new Float set to x, with precision 53 and
    rounding mode ToNearestEven. NewFloat panics with ErrNaN if x is a NaN.

func (z *Float) SetFloat64(x float64) *Float
    SetFloat64 sets z to the (possibly rounded) value of x and returns z. If z's
    precision is 0, it is changed to 53 (and rounding will have no effect).
    SetFloat64 panics with ErrNaN if x is a NaN.
```

**Comment by dannypsnl** [comment]
I find out the problem, Go internal implementation always using `0x7FF8000000000001`

```go
const (
	uvnan    = 0x7FF8000000000001
// ...
)
// ...
// NaN returns an IEEE 754 ``not-a-number'' value.
func NaN() float64 { return Float64frombits(uvnan) }
```

and `const_float.go` directly invoke it, therefore, sign bit information would be lost.
