### ISSUE TITLE
tag release v0.3.1 which includes LLVM 10.0 support

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#145]
This is a meta issue to track the progress of tagging a new release for `llir/llvm`.

With @dannypsnl's work on adding LLVM 10.0 support for `llir/llvm`, we are now ready to tag a new stable release of `llir/llvm`.

The [v0.4.x](https://github.com/llir/llvm/milestone/7) release is targetted for an API update (potential overhaul) of `llir/llvm` where we focus on adding data flow analysis.

In any release, we will use the patch version (i.e. the `x` in `vA.B.x`) to update `llir/llvm` to stay in sync with LLVM release versions.

The intention is to stay on the `v0.x.x` release version at least until after we have added a solid data flow analysis API, and have had time to experiment with it to see if it feels right or need to be redesigned.

There may be other big areas that we need to consider and design APIs for `llir/llvm` that may need some time to mature, e.g. when we start doing optimization implementations (dead code analysis, constant propagation, etc). These would also live in the `v0.x.x` release version until we have had time to experiment with them to build compilers, and other analysis tools. It is also possible to envision that such algorithms (e.g. optimization) may live in an entirely different repository than `llir/llvm`, and would just be another user of `llir/llvm` instead of being part of the main repo. Time will tell.

For now, lets get ready to tag the new release of `llir/llvm` which includes support for LLVM 10.0.

And thanks @dannypsnl for working on making this happen! :)

Cheers,
Robin

**Comment by mewmew** [comment]
What things do we need to do before tagging the `v0.3.1` release?

- We can add a new entry to the [release history(https://github.com/llir/llvm/blob/master/HISTORY.md).
- Anything else?

**Comment by dannypsnl** [comment]
Maybe we can add a brief mapping llir/llvm version to llvm version in README?

**Comment by mewmew** [comment]
> Maybe we can add a brief mapping llir/llvm version to llvm version in README?

Soudns good.

**Comment by mewmew** [comment]
The v0.3.1 release has now been tagged :) Great work @dannypsnl!

**Comment by dannypsnl** [comment]
@mewmew I delete discord channel accidentally... can you add me back? 😂
