### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#150]
@mewmew The point is, should we close the example test? I feel it failed frequently but didn't provide useful information.

**Comment by mewmew** [comment]
> @mewmew The point is, should we close the example test? I feel it failed frequently but didn't provide useful information.

Ah, I think you may be right. The reason it fails often is that it pretty prints the entire struct, and if we change/add a new field it will fail.

I still think it is useful as an example for new users of the API as it gives a lot of raw detail of how these struct look. When I start to use a new API this is the kind of example I want to have access to.

But perhaps we can convert it from a test + example to just an example?

**Comment by dannypsnl** [comment]
Just an example sounds good.🙂

**Comment by mewmew** [comment]
> Just an example sounds good.slightly_smiling_face

great :) @dannypsnl would you like to prepare a PR for this?

**Comment by dannypsnl** [comment]
`ir/main_test.go`?
