### ISSUE TITLE
Implement floating point numbers

### ISSUE THREAD

**Issue by sangisos** [llir/llvm#16]
To be able to Implement the instructions taking floats, first floats need to be implemented. This Issue tracks all work related to implementing the float type and instructions.
[Floating point types](http://llvm.org/docs/LangRef.html#floating-point-types):
- [x] half 16-bit floating point value
- [x] float     32-bit floating point value
- [x] double    64-bit floating point value
- [x] fp128     128-bit floating point value (112-bit mantissa)
- [x] x86_fp80  80-bit floating point value (X87)
- [x] ppc_fp128     128-bit floating point value (two 64-bits)

[Floating point constants](http://llvm.org/docs/LangRef.html#simple-constants):
- [x] Decimal point
- [x] Scientific
- [x] Hex

Instructions:
- [x] [fadd-instruction](http://llvm.org/docs/LangRef.html#fadd-instruction)
- [x] [fsub-instruction](http://llvm.org/docs/LangRef.html#fsub-instruction)
- [x] [fmul-instruction](http://llvm.org/docs/LangRef.html#fmul-instruction)
- [x] [fdiv-instruction](http://llvm.org/docs/LangRef.html#fdiv-instruction)
- [x] [frem-instruction](http://llvm.org/docs/LangRef.html#frem-instruction)
- [x] [fcmp-instruction](http://llvm.org/docs/LangRef.html#fcmp-instruction)

[fast-math-flags](http://llvm.org/docs/LangRef.html#fast-math-flags)
- [ ] nnan
- [ ] ninf
- [ ] nsz
- [ ] arcp
- [ ] fast

**Comment by mewmew** [comment]
Update as of 2016-12-01.

The [parser branch](https://github.com/llir/llvm/tree/parser) has gained support for most aspects of floating-point numbers (latest commit 778a42e4b77295a855870576029d993ed848aede).

The only remaining aspects are fast-math-flags. The 0.2 release is intended to focus on a simplified subset of LLVM IR, as covered by the data types defined in https://godoc.org/github.com/llir/llvm/ir.

A future release will include support for further details of the LLVM IR language, including fast-math-flags, and other instructions specific flags, such as `nsw` and `nuw` of binary operations.

The work to implement a the full subset of LLVM IR is covered by issue #7, and the specific issue to implement fast-math-flags has been move to that issue for future tracking.

Closing this issue for now, as the intended subset of floating-point instructions have been implemented for the release of v0.2.

@sangisos and @7i, great work! :)
