### ISSUE TITLE
Is it possible to interact with Go runtime without interpreter?

### ISSUE THREAD

**Issue by yingfeng** [llir/llvm#174]
Similar with this [issue](https://github.com/llir/llvm/issues/18),  suppose there is an IR generated from other languages, since there does not exist an official Golang interpreter right now, is it possible to interact with go runtime through other mechanism? For example,  to build IR into golang shared library or plugin such that it could be dynamically loaded?

**Comment by mewmew** [comment]
Hi @yingfeng,

As for interpreting Go, I'd very much recommend Yaegi [[1]], [[2]]. It supports the full Go language specification and is a production quality interpreter.

When it comes to having LLVM IR compiled generated from other languages interact with LLVM IR of Go (and the Go runtime), I would recommend taking a look at Gollvm [[3]], the official LLVM-based Go frontend. It *should* be possible to hook these up to work and interact as you see fit, of course taking careful consideration of calling conventions, memory handling, etc.

Oh, and if you do venture into trying this out, I'd definitely be curious to learn of your experiences and how it went! Even if it did not work, so we get more insight into what works and what doesn't.

Wish you all the best and happy hacking!

Cheerful regards,
Robin

[1]: https://github.com/traefik/yaegi
[2]: https://traefik.io/blog/announcing-yaegi-263a1e2d070a/
[3]: https://go.googlesource.com/gollvm/

**Comment by yingfeng** [comment]
Thanks a lot for your suggestion !

**Comment by mewmew** [comment]
> Thanks a lot for your suggestion !

Glad to. Remember to report back on how your experiments go :)

**Comment by yingfeng** [comment]
We plan to provide user defined functions for sql engine, but it's not our current focus right now since we need to deliver the engine itself at first, we might return to this issue several months later.  If you are interested in our work, you could ping me through my email :)
