### ISSUE TITLE
let fulltest and coverage can be triggered manually

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#175]
As title, add

```yml
# allow you to run this workflow manually from tab
workflow_dispatch:
```

into `fulltest.yml` and `coverage.yml`.

**Comment by mewmew** [comment]
Sound good, feel free to submit a commit. However, lets first handle https://github.com/llir/llvm/commit/3d1eaf305febd6f3d52757a76d5247f3fa045813#comments and potentially force reset the master branch 2 commits back, before adding this.
