### ISSUE TITLE
How to make "..." arg type?

### ISSUE THREAD

**Issue by Nv7-GitHub** [llir/llvm#178]
I want to call printf. When using clang, it emits:
```llvm
declare i32 @printf(i8*, ...)
```

How do I make a new function with llir, with `...` as the argument?

**Comment by mewmew** [comment]
Hi @Nv7-GitHub,

Glad to see you experimenting with LLVM IR in Go :)

> How do I make a new function with llir, with ... as the argument?

Set the [Variadic](https://pkg.go.dev/github.com/llir/llvm/ir/types#FuncType.Variadic) field of [ir.Func.Sig](https://pkg.go.dev/github.com/llir/llvm/ir#Func.Sig) to `true`.

```go
package main

import (
	"fmt"

	"github.com/llir/llvm/ir"
	irtypes "github.com/llir/llvm/ir/types"
)

func main() {
	i32Type := irtypes.I32
	i8PtrType := irtypes.NewPointer(irtypes.I8)
	param := ir.NewParam("format", i8PtrType)
	printfFunc := ir.NewFunc("printf", i32Type, param)
	printfFunc.Sig.Variadic = true

	module := ir.NewModule()
	module.Funcs = append(module.Funcs, printfFunc)
	fmt.Println(module)
}
```

Cheers,
Robin

**Comment by mewmew** [comment]
Closing this issue for now as resolved. Hope it helped. And if not, just write a comment and we can re-open it.

Cheers,
Robin
