### ISSUE TITLE
How do I call LLVM IR?

### ISSUE THREAD

**Issue by Nv7-GitHub** [llir/llvm#181]
I compiled some C code to LLVM. Is there a way to use this LLVM code as raw text (for example, one of the functions)?

**Comment by mewmew** [comment]
You can either use the official LLVM interpreter `lli` to run LLVM IR code. Or you can compile and link the LLVM IR code to a binary executable, using e.g. `clang`.

Given `foo.ll`:
```llvm
define i32 @main() {
	ret i32 42
}
```

Run through `lli` as follows:
```bash
lli foo.ll
```

Compile using `clang` and run binary executable as follows:
```bash
clang -o foo foo.ll
./foo
```

In both cases the status code will be 42. Which can be echoed e.g. using `echo $?` in bash or `echo $status` in Fish.

Cheers,
Robin

**Comment by mewmew** [comment]
Or do you mean to use within `llir/llvm`? If so, take a look at [llir/llvm/asm.ParseFile](https://pkg.go.dev/github.com/llir/llvm/asm#ParseFile).

**Comment by Nv7-GitHub** [comment]
After using ParseFile, how do you get a function from the module?

**Comment by dannypsnl** [comment]
> After using ParseFile, how do you get a function from the module?

https://pkg.go.dev/github.com/llir/llvm@v0.3.3/ir#Module

There has a field called `Funcs`
