### ISSUE TITLE
git: commit hook

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#185]
I think a template commit message would be nice, and using direnv can load hooks automatically, what do you think? @mewmew

**Comment by dannypsnl** [comment]
Template
```
# title: message
ci: 

# body
```

**Comment by mewmew** [comment]
I'm ok with following the commit message style used by the Go project (https://github.com/golang/go/commits/master).

```
pkg/name: short commit message

Longer description of change (optional).

Ref to specific issue (optional).
```

Personally, I don't think I need a commit hook for this. Feel free to configure one for your own use.

Cheers,
Robin
