### ISSUE TITLE
irutil: data layout configuration

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#189]
It would be good to implement parsing and handling of data layout strings, building upon this API, and add such functionality to irutil.

**Comment by mewmew** [comment]
ref: #66

**Comment by mewmew** [comment]
This issue requires parsing the LLVM [data layout](https://llvm.org/docs/LangRef.html#data-layout) string to determine the memory layout, so we can handle padding of struct fields and array elements. Having implemented parsing of LLVM data layout strings, implementing support for composite types for the [irutil.Layout](https://pkg.go.dev/github.com/llir/irutil#Layout) interface should be rather straight forward.

**Comment by svvivek** [comment]
> It would be good to implement parsing and handling of data layout strings, building upon this API, and add such functionality to irutil.

I have tried writing one, please check it out @ https://github.com/llir/irutil/pull/4

**Comment by svvivek** [comment]
> > It would be good to implement parsing and handling of data layout strings, building upon this API, and add such functionality to irutil.
> 
> I have tried writing one, please check it out @ [llir/irutil#4](https://github.com/llir/irutil/pull/4)

Now that the PR is merged, this issue can be closed right ?

**Comment by mewmew** [comment]
> Now that the PR is merged, this issue can be closed right ?

Indeed. Great work1

We can now add methods to the `irutil.DataLayout` to implement the [irutil.Layout](https://pkg.go.dev/github.com/llir/irutil#Layout) interface.

Have a great week :) Happy wishes from Sweden.

Cheers,
Robin
