### ISSUE TITLE
Use tracking

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#19]
The issue is intended to track discussions and experimental implementation related to use tracking.

The C++ API of LLVM defines the concepts of a `Use` and a `User`. A `Use` is an edge between a used value and its user. Each `User` has a number of operands which specify the `Use`d values. Pseudo code follows:

```go
type Value interface {
	Uses() []Use
}

type Use interface {
	OpNum() int
	User() User
	Usee() Value
}

type User() interface {
	NOps() int
	Op(i int) Value
	SetOp(i int, v Value) error
}
```

Anyone is invited to join the discussion. How would users of the API which to use it? May it be implemented by a dedicated package separate from the `ir` package? How would the interaction work? May there co-exist several implementations of use-tracking, and is this ever useful?

**Comment by andybalholm** [comment]
The simplest thing that could possibly work would be to make Instructions and Terminators fulfill this interface:

```go
interface ValueUser {
    ValuesUsed() []Value
}
```

Then users of the package could implement their own use tracking without needing a giant type switch; they could treat all ValueUsers alike.

But once you've done that, building a map from Values to ValueUsers would be simple enough that you might as well do it too:

```go
func FindUsers(f *ir.Func) map[Value][]ValueUser
```

**Comment by andybalholm** [comment]
Sounds good to me. I'm not sure if ValueUser is the best name for the interface if the method is named Operands, but I don't know what name to suggest.

**Comment by mewmew** [comment]
> Sounds good to me. I'm not sure if ValueUser is the best name for the interface if the method is named Operands, but I don't know what name to suggest.

I think it's fine. If we figure out a better one while implementing the feature, we can change it.

How about `value.User`? This matches the name used in the official LLVM API (ref: https://llvm.org/doxygen/classllvm_1_1User.html).

**Comment by dannypsnl** [comment]
So we only need to merge operands branch?

**Comment by andybalholm** [comment]
Yes, I think `value.User` would be fine.

**Comment by mewmew** [comment]
> So we only need to merge operands branch?

Almost. The operands branch still used non-mutable lists for operands. I made a new PR returning a mutable list from the `Operands` method. Otherwise, they should be identical.

Cheers,
Robin
