### ISSUE TITLE
Branch release?

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#201]
SInce #199, I want to backport `DISPFlags` to v10 and v11, thus we better based on release branches to have

1. v0.3.2.1 ~> 10
2. v0.3.3.1 ~> 11

**Comment by mewmew** [comment]
Personally, I don't know if we should be supporting and backporting to older versions of LLVM, as this could require a lot of maintenance for our small team.

When syntax changes between versions in LLVM, I think it is better to include a *how to* documentation to help users upgrade their old LLVM IR syntax to newer versions of LLVM. This can be done using the official LLVM tool chain. E.g. using `opt` from a newer version of LLVM.
```bash
opt -S -o new_synatx.ll old_syntax.ll
```

@dannypsnl, if however you wish to backport and continue to support older releases, then I suggest we use the branch names e.g. `release-branch.llvm10`, `release-branch.llvm11` in those cases.

Cheers,
Robin

**Comment by dannypsnl** [comment]
Yes, team size is a big problem here XD, close for now. If anyone wants to have backporting, feel free to reopen it.
