### ISSUE TITLE
used by

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#206]
Since GitHub provides https://github.com/llir/llvm/network/dependents?package_id=UGFja2FnZS0yMjY0ODM3NDQ4, do we still want https://github.com/llir/llvm#users?

**Comment by mewmew** [comment]
> Since GitHub provides https://github.com/llir/llvm/network/dependents?package_id=UGFja2FnZS0yMjY0ODM3NDQ4, do we still want https://github.com/llir/llvm#users?

I still think it's valuable to have a *users* section, as it also provides a short description of the project. Still, using the [network dependency graph](https://github.com/llir/llvm/network/dependents?package_id=UGFja2FnZS0yMjY0ODM3NDQ4) is a cool way to find users of `llir/llvm`.
