### ISSUE TITLE
reject non-pointer type for global

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#208]
If we define a new global
```go
module.NewGlobal(name, types.I8)
```
it would cause an error that `global variable reference must have pointer type`

Thus, I think this check is acceptable.

**Comment by dannypsnl** [comment]
BTW, do you think https://github.com/dannypsnl/extend is a good way to do `irsem`?

**Comment by mewmew** [comment]
> BTW, do you think https://github.com/dannypsnl/extend is a good way to do irsem?

I consider [dannypsnl/extend](https://github.com/dannypsnl/extend) to be closer to `irutil`/`irgen`.

For `irsem` we would do a traversal over an entire module, validating it's semantics, e.g. by calling `irsem.Verify`.

ref: https://github.com/llir/llvm/issues/65#issuecomment-464938676

```go
// Package sem performs semantic analysis of LLVM IR modules.
package sem

// Verify performs type-checking and semantic analysis of the given module to
// verify consistency and correctness.
func Verify(m *ir.Module) error
```

**Comment by dannypsnl** [comment]
https://github.com/llir/irsem solution

**Comment by mewmew** [comment]
re: https://github.com/llir/irsem/blob/cda51dc46b55de911196e57f5848c5c828edf1a9/verify.go#L11

@dannypsnl, are you sure this semantic is not valid in LLVM IR? I think it is.

```go
package main

import (
	"fmt"
	"log"

	"github.com/llir/llvm/ir"
	"github.com/llir/llvm/ir/constant"
	"github.com/llir/llvm/ir/types"
)

func main() {
	if err := foo(); err != nil {
		log.Fatalf("%+v", err)
	}
}

func foo() error {
	m := ir.NewModule()
	x := m.NewGlobalDef("x", constant.NewInt(types.I32, 42))
	f := m.NewFunc("main", types.I32)
	entry := f.NewBlock("entry")
	result := entry.NewLoad(types.I32, x)
	entry.NewRet(result)
	fmt.Println(m)
	log.Println("x.ContentType:", x.ContentType)
	log.Println("x.Type():", x.Type())
	return nil
}
```

Outputs the debug message:
```
x.ContentType: i32
x.Type(): i32*
```

And the LLVM IR:

```llvm
@x = global i32 42

define i32 @main() {
entry:
	%0 = load i32, i32* @x
	ret i32 %0
}
```

The output LLVM IR is *valid* when run through `lli`

```
# lli a.ll ; echo $?
42
```

As such, the type of `*ir.Global.ContentType` may be a non-pointer type, and this is still valid. I think the only thing is we have to reference global variables using pointer types, that is, when you load from a global variable, or store to a global variable, then the global has pointer type (and not it's content type).

Could you provide a full test case/example which demonstrates the broken behaviour?

Cheers,
Robin

**Comment by dannypsnl** [comment]
```go
mod := ir.NewModule()
mod.NewGlobal("hello", types.I8)
mod.NewGlobalDef("x", constant.NewInt(types.I32, 42))
mf := mod.NewFunc("main", types.I32)
mb := mf.NewBlock("")
mb.NewRet(constant.NewInt(types.I32, 0))
```

write to temporary llvm file

```llvm
@hello = global i8
@x = global i32 42

define i32 @main() {
0:
	ret i32 0
}
```

compile

```
llc: error: llc: tmp.ll:2:1: error: global variable reference must have pointer type
@x = global i32 42
^
```

**Comment by dannypsnl** [comment]
But have to notice, if we only write
```go
mod.NewGlobal("hello", types.I8)
```
compile produces
```
llc: error: llc: tmp.ll:3:1: error: expected value token
```

**Comment by mewmew** [comment]
Ah, it's missing `external`.

```diff
-@hello = global i8
+@hello = external global i8
 @x = global i32 42
 
 define i32 @main() {
 0:
 	ret i32 0
 }
```

Therefore, the `@x` is read as the initializing value of `@hello`.

**Comment by dannypsnl** [comment]
> Ah, it's missing `external`.
> 
> ```diff
> -@hello = global i8
> +@hello = external global i8
>  @x = global i32 42
>  
>  define i32 @main() {
>  0:
>  	ret i32 0
>  }
> ```
> 
> Therefore, the `@x` is read as the initializing value of `@hello`.

Emmm, should we fix this automatically? Or check in irsem

I think the check would be a global missing initializer should with external

**Comment by mewmew** [comment]
> Emmm, should we fix this automatically? Or check in irsem

The check can be added to irsem. If `global.Init == nil` and `global.Linkage` is the zero value (`LinkageNone`), or something along those lines.

**Comment by dannypsnl** [comment]
Then please check [30da92f3d2381f91fd7af9edfbb5633b49a647d0](https://github.com/llir/irsem/commit/30da92f3d2381f91fd7af9edfbb5633b49a647d0), if ok then I close this issue.

**Comment by mewmew** [comment]
LGTM, with minor comment https://github.com/llir/irsem/commit/30da92f3d2381f91fd7af9edfbb5633b49a647d0#r62298445
