### ISSUE TITLE
How to have two structs referencing eachother

### ISSUE THREAD

**Issue by RedCubeDev-ByteSpace** [llir/llvm#224]
Hello there 👋

I'm currently working on a compiler using this package and have hit a little road block while working on classes.
I would like two classes (which are represented as structs) being able to reference eachother, so A having a pointer to B and B having a pointer to A but I couldn't figure out how to implement that using this library, as they need to be defined in some order and as far as I know typedefs are immutable after being created.

I'm sure theres a way of doing it that I just havent thought of yet haha

Heres a C++ example of exactly what I'm trying todo:
```cpp
class A;
class B;

class A {
    public:
    B *num;
};

class B {
    public:
    A *num;
};
```

Compiling to:
```llvm
%class.A = type { %class.B* }
%class.B = type { %class.A* }
```

Hope someone here can help me out!

**Comment by dannypsnl** [comment]
For short(I’m not with my computer now), I believe you will just take the type back from module instance.

**Comment by mewmew** [comment]
Hi @RedCubeDev-ByteSpace,

Happy to see you playing around with LLVM IR : )

Adding a bit to what @dannypsnl wrote.

Self-referential types, and circular references are always a bit difficult to deal with. That being said, it should be possible to do what you wish as follows:

```go
package main

import (
	"fmt"

	"github.com/llir/llvm/ir"
	"github.com/llir/llvm/ir/types"
)

func main() {
	m := ir.NewModule()
	classAType := &types.StructType{}
	classBType := &types.StructType{}
	classAPtrType := types.NewPointer(classAType)
	classBPtrType := types.NewPointer(classBType)
	classAType.Fields = append(classAType.Fields, classBPtrType)
	classBType.Fields = append(classBType.Fields, classAPtrType)
	m.NewTypeDef("class.A", classAType)
	m.NewTypeDef("class.B", classBType)
	// %class.A = type { %class.B* }
	// %class.B = type { %class.A* }
	fmt.Println(m)
}
```

Note, there is nothing "special" about type definitions, they are just a regular [ir/types.Type](https://pkg.go.dev/github.com/llir/llvm/ir/types#Type) with a name set. The type is then appended to the [TypeDefs](https://pkg.go.dev/github.com/llir/llvm/ir#Module.TypeDefs) field of [ir.Module](https://pkg.go.dev/github.com/llir/llvm/ir#Module) as regular.

From running the command `go doc -src github.com/llir/llvm/ir.Module.NewTypeDef`:
```go
package ir // import "github.com/llir/llvm/ir"

// NewTypeDef appends a new type definition to the module based on the given
// type name and underlying type.
func (m *Module) NewTypeDef(name string, typ types.Type) types.Type {
	typ.SetName(name)
	m.TypeDefs = append(m.TypeDefs, typ)
	return typ
}
```

(That's how type definitions are defined.)

So you can just set the name after you're done adding all the circular reference types to the [StructType.Fields](https://pkg.go.dev/github.com/llir/llvm/ir/types#StructType.Fields) slice.

Happy coding!

Cheers,
Robin

**Comment by dannypsnl** [comment]
@mewmew Do you think we need `GetFuncByName(name string)` and `GetTypeByName(name string)`?

**Comment by mewmew** [comment]
> @mewmew Do you think we need GetFuncByName(name string) and GetTypeByName(name string)?

These would be easy to implement in `irutil`. The implementation may either just do a `range` loop over the slice and check the name.

Or, if the order of declarations and definitions does not matter, we could sort them alphanumerically and then use binary search. Probably this approach is overkill and we should also have to make sure to keep the list sorted after inserting new elements. So, if this is added to `irutil`, I'd suggest going with the simpler approach of just using a `range` loop.

Cheers,
Robin
