### ISSUE TITLE
How to convert to exe?

### ISSUE THREAD

**Issue by sam-the-programmer** [llir/llvm#225]
If I create a translator for my programming language to LLVM IR in Go, how can I turn that LLVM IR to an executable, preferably using a go library (but can use other methods if necessary)

**Comment by dannypsnl** [comment]
I think the easiest is invoking `llc` via system API.

**Comment by mewmew** [comment]
As @dannypsnl pointed out, the official LLVM toolchain is used for optimizing LLVM IR and producing executables from LLVM IR.

For a given LLVM IR file `foo.ll`, to produce a binary, run:

```bash
# Produce foo binary from LLVM IR.
clang -o foo foo.ll
```

For a given LLVM IR file `foo.ll`, to optimize the LLVM IR, run:

```bash
# Optimize foo.ll LLVM IR.
opt -O3 -S -o foo_opt.ll foo.ll
```

And, as mentioned, if you want to run this from Go, use [os/exec](https://pkg.go.dev/os/exec#example-Command).

Cheers,
Robin

**Comment by sam-the-programmer** [comment]
Thank you, everyone!
