### ISSUE TITLE
Support specifying linkage type for globals and functions

### ISSUE THREAD

**Issue by dominikh** [llir/llvm#23]
Per https://llvm.org/docs/LangRef.html#linkage-types global variables and functions can have linkage types. Trying to generate IR (as a compiler frontend), this is a required feature.

Unless I've been particularly blind, setting the linkage type isn't currently possible.

**Comment by mewmew** [comment]
Thanks @dominikh for the heads up! With a clear use case in mind, linkage will definitely be added for to the IR for functions and globals. It was half-way implemented in the IR package before (rev d299b42d1047c54f1f674a73dcfa1ba62a2e90a7), but other features were favoured for the sake of time. Now, seems to be the time to make linkage a first class citizen of the IR package as well.

I have a busy week coming up, but would be happy to tackle this in the next few weeks. If you feel like contributing, this would be a lovely PR to review :)

Cheers /u

**Comment by mewmew** [comment]
As of #36, support for linkage on global variables (and functions) have been added.
