### ISSUE TITLE
Request: create executable with embedded assembler

### ISSUE THREAD

**Issue by thewh1teagle** [llir/llvm#239]
Does it possible to produce the final executable directly? eg. maybe embedding clang library and call some functions to produce the final executable directly instead of relying on installed clang.

Currently I use 

```console
clang -o main main.ll
```

**Comment by mewmew** [comment]
Hi @thewh1teagle,

Glad to see you are working on LLVM IR projects.

One of the main motivations behind this project was to not have external C++ dependencies, to facilitate working with the library (e.g. cross compilation, go-get, etc).

That being said, the [official Go bindings for LLVM](https://pkg.go.dev/github.com/llvm-mirror/llvm/bindings/go/llvm) does have the functionality you're looking for! As does the [tinygo library for LLVM](https://pkg.go.dev/tinygo.org/x/go-llvm). Have a look at either of these.

For some more details, see #238.

Happy coding!

Cheerful regards,
Robin
