### ISSUE TITLE
astx/fix: doesn't handle quoted names correctly

### ISSUE THREAD

**Issue by dominikh** [llir/llvm#24]
**Input:**

```
define void @fn() {
    call void @"quoted1"()
    call void @"quoted 2"()
    ret void
}

declare void @"quoted1"()
declare void @"quoted 2"()
```

**Output:**

```
panic: unable to locate global identifier "\"quoted1\""

goroutine 1 [running]:
github.com/llir/llvm/asm/internal/astx.(*fixer).getGlobal(0xc421d896a8, 0xc420012381, 0x9, 0x5fa520, 0xc421d45360)
	/home/dominikh/prj/src/github.com/llir/llvm/asm/internal/astx/fix.go:345 +0x12c
[...]
```

getGlobal and getLocal in astx/fix.go do not handle quoted names correctly. The maps store unquoted names, but the lookup includes the surrounding quotes.

**Comment by mewmew** [comment]
This issue has been resolved in the latest revision of llir/llvm.

Given the input:

```llvm
define void @fn() {
    call void @"quoted1"()
    call void @"quoted 2"()
    ret void
}

declare void @"quoted1"()
declare void @"quoted 2"()
```

The following example program runs successfully:

```go
package main

import (
	"fmt"

	"github.com/llir/llvm/asm"
)

func main() {
	m, err := asm.ParseFile("foo.ll")
	if err != nil {
		panic(err)
	}
	fmt.Println(m)
}
```

And produces the following output:

```llvm
define void @fn() {
	call void @quoted1()
	call void @"quoted 2"()
	ret void
}

declare void @quoted1()

declare void @"quoted 2"()
```

Notice that identifiers in the output are only quoted if required (i.e. containing special characters or spaces).

Closing this issue for now. If you notice any other issues, just re-open or report back in a new issue.

Cheers,
Robin
