### ISSUE TITLE
Add an Operands() function for inspecting operands of instructions

### ISSUE THREAD

**Issue by pwaller** [llir/llvm#42]
I think it would be very useful to have a way of finding the operands of an instruction.

Here's an example of a code generator which makes such a function.

https://gist.github.com/pwaller/255654cd78b77484a02cdfaa6a22237c

In the end, I don't know exactly how I feel about it (especially the code generation part...).

But I guess this gets me quite close to being able to implement a simple dead code pass which can kill unused private functions.

Example use:

```go
func loopOperands(irModule *ir.Module) {
	for _, f := range irModule.Funcs {
		for _, bb := range f.Blocks {
			for _, i := range bb.Insts {
				log.Println("inst:", i.Def())
				var tmp [16]irvalue.Value
				for _, o := range ir.Operands(tmp[:0], i) {
					log.Println("  op:", o)
				}
			}
		}
	}
}
```

I note that  Operands() could *almost* return pointers to values, so that the references were mutable. However, this is broken. The only reason it is broken that I can find is the `Scope` field on `InstCatchPad` and `InstCleanupPad`. I think if we want to be able to obtain mutable references to Operands, those fields should become of types `value.Value`. I guess there are pros and cons to that. But if you want mutable references to operands I think the alternatives are going to be much uglier.

**Comment by pwaller** [comment]
@mewmew here's a quick attempt at trivial dead code elimination using this.

https://gist.github.com/pwaller/a2d49c626aa909ecd24ba05b2a96a3c3

**Comment by mewmew** [comment]
Marking this with the v0.4 milestone as it pertains to analysis, which is the focus of the v0.4 release.

For now, I think we can experiment a bit at a separate repository. @pwaller would you care creating llir/analysis for this purpose and add an initial implementation of `Operands`? I realize we can't add methods to instructions with this approach, but at least we can use it to figure out the other aspects, such as memory allocations, API usage etc.

My initial thought is that we may want to implement proper support for use-def tracking, and given this, `Operands` would most likely not be needed for dead-code elimination, as you could simply look up the uses of each function and global, and if they are not used in other functions being used, them simply mark them for removal.

**Comment by pwaller** [comment]
I'll hold off on doing this for now. I'd prefer to avoid (myself) putting something in the llir namespace until it's closer to an API we want to support.

**Comment by mewmew** [comment]
> I'll hold off on doing this for now. I'd prefer to avoid (myself) putting something in the llir namespace until it's closer to an API we want to support.

Sounds good. We can continue to experiment until, and of course keep open discussions until we get closer to something that may be generally usable and a good API for data flow analysis.
