### ISSUE TITLE
ir: rename Def method to LLString?

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#45]
Analogous to `fmt.GoStringer`, we could use `LLString` (or `LLVMString`) to have LLVM IR constructs print their own definition.

The main reason to switch is to free up the name `Def`, which we may want to use for use-def chains as part of the v0.4.0 release which focuses on data flow analysis.

**Comment by pwaller** [comment]
Please can I take ahold of this one, since I'm still experimenting with #41 and this would interfere. Ping me if nothing happens and you want to get a move on with this.

**Comment by mewmew** [comment]
> Please can I take ahold of this one, since I'm still experimenting with #41 and this would interfere. Ping me if nothing happens and you want to get a move on with this.

Sounds good to me.

**Comment by pwaller** [comment]
OK, thanks for the heads up. Unknown if I will have time to finish things before then, I'm a bit swamped at the moment. We'll see.

**Comment by mewmew** [comment]
> OK, thanks for the heads up. Unknown if I will have time to finish things before then, I'm a bit swamped at the moment. We'll see.

Ok, feel no stress. If you get to it, you do. Otherwise, it's fine. I'll ping you sometime next week and see how your doing :) Cheers /u

**Comment by mewmew** [comment]
Hi @pwaller! Hope you've had a most cheerful winter holidays thus far :)

I got into the mood of working on llir, so I may try to get this in during the day. I hope it should not be too difficult to rebase for you later if you want to continue work on the `WriteTo` methods. I will essentially just do a search and replace for `Def` to `LLString`.

Cheers,
Robin
