### ISSUE TITLE
How to create malloc in llir/llvm?

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#52]
Basically what I need is something like this:
https://godoc.org/llvm.org/llvm/bindings/go/llvm#Builder.CreateMalloc

In my case, I'm trying to create a currying function call, it would need to store parameters in a structure

**Comment by pwaller** [comment]
I'm afraid the answer is likely not what you're looking for, but at the moment to the best of my knowledge you need to implement something like this, which is effectively what happens in the bindings you linked to. That's what's going on under the hood:

https://github.com/llvm-mirror/llvm/blob/42f44e618270417470aada33ccecade8eb196b6f/lib/IR/Instructions.cpp#L432-L512

The `llir/llvm` package doesn't have much notion of 'runtime' at the moment, and `malloc` is essentially a runtime function call.

I can imagine that at some point `llir` may have an IR building package somewhere that would help you do this sort of thing. I'm unsure at this point where it would live. @mewmew may also have some opinions on this.

**Comment by zegl** [comment]
I don't know if this answers your question, but:

I've been using the glibc malloc [like this](https://github.com/zegl/tre/blob/dd6fba5543100711d4e7cc0a0e85886c660f7704/compiler/compiler/external_funcs.go#L41) in _tre_. I'm then able to use the malloc function [like this](https://github.com/zegl/tre/blob/4ffcc6cd95bfaf85b758d8890e1d7810fc70e750/compiler/compiler/struct.go#L121-L122).

```go
mallocFunc := module.NewFunc("malloc",
    types.NewPointer(types.I8),
    ir.NewParam("", types.I64),
)

mallocatedSpaceRaw := block.NewCall(mallocFunc, constant.NewInt(types.I64, structType.Size()))
alloc := block.NewBitCast(mallocatedSpaceRaw, types.NewPointer(structType.LLVM()))
```

**Comment by mewmew** [comment]
Perfect! It's brilliant to have a quick answer to this. I didn't know it myself. Closing this issue as it seem to have been resolved.

Cheers,
/u

**Comment by mewmew** [comment]
> I can imagine that at some point llir may have an IR building package somewhere that would help you do this sort of thing. I'm unsure at this point where it would live. @mewmew may also have some opinions on this.

Indeed. An package with IR builder like functionality will most likely live somewhere in `llir` in the future. Currently we focus on getting the *core* just right, giving full support for the various language constructs of LLVM IR.

When it comes to the IR builder package, we are essentially collecting experiences from any Gopher playing with LLVM IR to build compilers and other tools and libraries. It may very well be that common practices emerge that are similar but also unlike those used in the C++ builder API, and that is what we want. To see what such an API may look, if re-designed for the Go ecosystem.

The predominant approach today, seem to be to create a structure which tracks the context of the IR generator/builder (i.e. current function being generated, current basic block, etc); e.g. as is done by the [Compiler](https://godoc.org/github.com/zegl/tre/compiler/compiler#Compiler) type of tre:

From https://github.com/zegl/tre/blob/f12f93021cbd5344ceb4f204997b95ec45d1db9d/compiler/compiler/compiler.go#L41:

```go
type Compiler struct {
	module *ir.Module
	...
	contextBlock *ir.BasicBlock
	...
}
```

A similar approach it taken by uc, which uses [irgen.Function]() to keep the context of functions being generated:

From https://github.com/mewmew/uc/blob/0c45fe07f88905b95c012dba4acd700a258d674d/irgen/irgen.go#L49:

```go
// A Function represents an LLVM IR function generator.
type Function struct {
	// Function being generated.
	*ir.Function
	// Current basic block being generated.
	curBlock *BasicBlock
	...
```

As we gain more experience using llir to develop compilers and analysis tools, we will also see what approaches for IR generation look clean, are general and powerful. We'll probably iterate a few times before declaring an "official" llir `irgen` / `builder` package, but we'll definitely look for good examples to point to and learn from.

At least, those are the thoughts on the top of my head. Sometime similar would probably happen for `runtime` specific functionality, e.g. interaction with garbage collection, etc; as further tracked by #18.

**Comment by mewmew** [comment]
@zegl Cool, didn't know tre had [escape analysis](https://github.com/zegl/tre/blob/4ffcc6cd95bfaf85b758d8890e1d7810fc70e750/compiler/compiler/struct.go#L120) :)
