### ISSUE TITLE
ir: add type as first argument to NewStruct, NewArray and NewVector?

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#60]
Currently, the type of struct, array and vector constants is inferred by the elements and fields passed to their respective constructors. The idea was to make it easier for users to create these constants. However, there are valid cases where the user may which to pass a specific type to these constructors, especially the `NewStruct` constructor as struct types are equated by type identity and not structural equality.

Also for consistency with NewInt, NewFloat and other constructors of constants, we may wish to add a type as the first argument to the constructors `NewStruct`, `NewArray` and `NewVector`.

I'll leave this open for discussion, so we can collect different benefits and drawbacks with the various approaches.

To be specific, this issue suggests to update the [constant.NewStruct](https://godoc.org/github.com/llir/llvm/ir/constant#NewStruct), [constant.NewArray](https://godoc.org/github.com/llir/llvm/ir/constant#NewArray) and [constant.NewVector](https://godoc.org/github.com/llir/llvm/ir/constant#NewVector) constructors, as follows:

```diff
 package constant

-func NewStruct(fields ...Constant) *Struct
+func NewStruct(t *types.StructType, fields ...Constant) *Struct

-func NewArray(elems ...Constant) *Array
+func NewArray(t *types.ArrayType, elems ...Constant) *Array

-func NewVector(elems ...Constant) *Vector
+func NewVector(t *types.VectorType, elems ...Constant) *Vector
```

**Comment by emersion** [comment]
Maybe `nil` could be passed to preserve the current behaviour?

**Comment by mewmew** [comment]
> Maybe nil could be passed to preserve the current behaviour?

That's true. Would have to think a bit before deciding to use `nil` for this, mostly because I've been bitten one to many times by nil dereferences in Go. But in the end, this may be the approach we are going for.

**Comment by pwaller** [comment]
I can see both sides of it. I like the inference. But I also like having a symmetrical API (with respect to `constant.New(Int|*)`.

So given that, I like having inference when a nil type is passed.

**Comment by mewmew** [comment]
Ok. We'll take this approach and document that `nil` can be used for inference.
