### ISSUE TITLE
Missing Type call?

### ISSUE THREAD

**Issue by pwaller** [llir/llvm#67]
Noticed the following.

https://github.com/llir/llvm/blob/10a64dac8a1a3c934a1028418224337743edef72/ir/inst_aggregate.go#L94-L98

I assume that this is just missing a `Type()` call?

**Comment by mewmew** [comment]
> I assume that this is just missing a `Type()` call?

I think you are right indeed. To "cache" the type, a call to `inst.Type()` should appear after the `// Compute type.` comment. Care to send a PR? :)
