### ISSUE TITLE
Can we update the tag more frequently for go module users?

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#68]
Since this package would get the important fix in a new version, and API also would be improved by the release, can we make the `pre` tag updating more frequently?

**Comment by mewmew** [comment]
Sure, I think we can tag a new pre-release. @pwaller, would you like to add a `v0.3.0-pre7` tag after #65 and #67?

**Comment by mewmew** [comment]
Hi @dannypsnl,

Just so you know, @pwaller just tagged `v0.3.0-pre7`.

Cheers,
Robin

**Comment by pwaller** [comment]
Feel free to ping this thread any time you want a new tag @dannypsnl. You may also be able to achieve what you want by saying `go get github.com/llir/llvm@master`, too.
