### ISSUE TITLE
wish: create alias automatically for functions with duplicate name

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#75]
## description

LLVM would create an alias for functions with a duplicate name, and I think this is pretty useful.
But currently `llir/llvm` won't do this but generated an invalid __llvm-ir__, I think better to follow the official implementation, or at least report the error for duplicate naming.

### llir/llvm:
```go
package main

import (
        "fmt"

        "github.com/llir/llvm/ir"
        "github.com/llir/llvm/ir/types"
)

func main() {
        mod := ir.NewModule()

        mod.NewFunc("add", types.I64)
        mod.NewFunc("add", types.I64)

        fmt.Printf("%s", mod)
}
```

generated llvm-ir:
```llvm
declare i64 @add()

declare i64 @add()
```
### The offical LLVM (C++ code):
```cpp
#include <memory>
#include <vector>

#include <llvm/IR/Module.h>

static llvm::LLVMContext context;

int main() {
  std::unique_ptr<llvm::Module> mod =
      llvm::make_unique<llvm::Module>("cool module", context);

  std::vector<llvm::Type *> args;
  auto function_type =
      llvm::FunctionType::get(llvm::Type::getInt64Ty(context), args, false);
  llvm::Function::Create(function_type, llvm::Function::ExternalLinkage, "add",
                         mod.get());
  llvm::Function::Create(function_type, llvm::Function::ExternalLinkage, "add",
                         mod.get());

  mod->print(llvm::errs(), nullptr);
}
```

generated llvm-ir:
```llvm
; ModuleID = 'cool module'
source_filename = "cool module"

declare i64 @add()

declare i64 @add.1()
```

**Comment by dannypsnl** [comment]
For now, could just create a `util` package contains the following codes(thanks @mewmew ):

```go
package irutil

// FixDups fixes duplicates identifiers in the module by adding uniquely
// differentiating numerical suffixes.
func FixDups(m *ir.Module) {
	names := make(map[string]uint64)
	// index global identifiers.
	addSuffix := func(v value.Named) {
		name := v.Name()
		for suffix := 1; ; suffix++ {
			newName := fmt.Sprintf("%s.%d", name, suffix)
			if _, ok := names[newName]; !ok {
				v.SetName(newName)
				names[newName] = 1
				return
			}
		}
	}
	for _, g := range m.Globals {
		names[g.Name()]++
	}
	for _, f := range m.Funcs {
		names[f.Name()]++
	}
	for _, a := range m.Aliases {
		names[a.Name()]++
	}
	for _, i := range m.IFuncs {
		names[i.Name()]++
	}
	for _, g := range m.Globals {
		if x := names[g.Name()]; x != 1 {
			addSuffix(g)
		}
	}
	for _, f := range m.Funcs {
		if x := names[f.Name()]; x != 1 {
			addSuffix(f)
		}
	}
	for _, a := range m.Aliases {
		if x := names[a.Name()]; x != 1 {
			addSuffix(a)
		}
	}
	for _, i := range m.IFuncs {
		if x := names[i.Name()]; x != 1 {
			addSuffix(i)
		}
	}
}
```

@mewmew Would you add these into the project? Might be `ir/util` or what?

**Comment by mewmew** [comment]
> @mewmew Would you add these into the project? Might be ir/util or what?

Perhaps later. For now would you keep the `irutil` package at yours? I.e. https://github.com/dannypsnl/irutil

I think later on we will see what patters are common across many users and integrate them into an irutil package. I think for now, keeping the shared API small is preferable.

However, I can be persuaded otherwise :)

**Comment by dannypsnl** [comment]
Closing since not needed right now? Feel free to reopen it if you need this.

@mewmew I saw **util** milestone is referring to this issue, do we want to implement this? Probably don't refer to issue if not ensure are going to implement? In case we can use the label. It depends on you, just want some conventions.

**Comment by mewmew** [comment]
> Closing since not needed right now? Feel free to reopen it if you need this.

Yeah, close for now. If it turns out many people needs this functionality we can make it generally available in `llir/irutil`.

> @mewmew I saw util milestone is referring to this issue, do we want to implement this? Probably don't refer to issue if not ensure are going to implement? We can use the label in case. It depends on you, just want some conventions.

Sure. I'll remove the `util` milestone. Makes better sense to track it as you suggested.
