### ISSUE TITLE
How to go about renaming locals?

### ISSUE THREAD

**Issue by pwaller** [llir/llvm#79]
* I'm loading some large pre-existing IR.
* I need to change an existing function call callee from `call void f()` to `call i8* g()`.
* The problem is that this suddenly means I have a new locally named thing in the middle of a block. I don't want to use that local name. It is unused.

This is the panic I'm getting at the moment. Is there an easy fix?

```
panic: unable to assign IDs of function "@foobar"; invalid local ID in function "@foobar", expected %40, got %39
```

My expectations were that this might work. If new names were needed after tweaking the IR during serialization, I had a mild expectation for them to be generated during serialization.

**Comment by mewmew** [comment]
Do you have a minimal code example I could try?

**Comment by pwaller** [comment]
```go
package main

                                                   
import (                                                          
        "os"                                                        
                                 
        "github.com/llir/llvm/asm"
        "github.com/llir/llvm/ir"
)        

func main() {                            
        m, err := asm.ParseString("<string>", `declare void @foo()

declare i8* @bar()

define i8 @run() {
  %0 = add i8 1, 2
  call void @foo()
  %1 = add i8 %0, 3
  ret i8 %1
}
`)

        if err != nil {
                panic(err)
        }

        nameToFunc := map[string]*ir.Func{}
        for _, f := range m.Funcs {
                nameToFunc[f.Name()] = f
        }

        for _, f := range m.Funcs {
                for _, b := range f.Blocks {
                        for _, i := range b.Insts {
                                if i, ok := i.(*ir.InstCall); ok {
                                        i.Callee = nameToFunc["bar"]
                                }
                        }
                }
        }

        os.Stdout.WriteString(m.String())
}
```

Output:

```
panic: invalid local ID in function "@run", expected %2, got %1
```

**Comment by hosewiejacke** [comment]
This has bitten me, too.

A possible workaround is to
1) pipe your existing IR through `opt -instnamer`
2) give your new symbols (randomly generated) names that start with a letter.

Maybe you can skip step 2.

**Comment by mewmew** [comment]
The issue here is that `@bar` returns a value and `@foo` does not. Therefore, the [ir.Func.AssignIDs](https://godoc.org/github.com/llir/llvm/ir#Func.AssignIDs) function reports the error `invalid local ID in function "@run", expected %2, got %1`.

Essentially, that error is added as a sanity check, so you don't have LLVM IR code that looks as follows:

```llvm
define void @foo() {
; <label>:0
	%1 = alloca i32
; <---- %2 is missing
	%3 = alloca i32
	...
}
```

or

```llvm
define void @foo() {
; <label>:0
	%1 = alloca i32
	%2 = alloca i32
	%2 = alloca i32 ; <---- %2 is used twice.
	%3 = alloca i32
	...
}
```

The easiest way to fix this is probably just to loop through the instructions and set their name to `""`, as that would cause the `ir.Func.AssignIDs` function to simply reassign new local IDs to the unnamed registers.

**Edit:** I noticed another issue now, the input LLVM IR assembly is incorrect. The entry basic block is named `%0` so the local variable associated with the `add` instruction should be named `%1`.

**Comment by mewmew** [comment]
This program generates the expected LLVM IR output. The main issue was that we have to reset the "cached" type of the call instruction, as that is only computed once, and given that we change the calle from `@foo` to `@bar`, the type of the call instruction needs to be updated.

However, this also uncovered an omission in the IR implementation (which has now been addressed in rev fe7863fc401b878a96481975b4b4f74bf321514a). Thanks!

```llvm
declare void @foo()

declare i8* @bar()

define i8 @run() {
; <label>:0
	%1 = add i8 1, 2
	%2 = call i8* @bar()
	%3 = add i8 %1, 3
	ret i8 %3
}
```

```go
package main

import (
	"os"

	"github.com/llir/llvm/asm"
	"github.com/llir/llvm/ir"
	"github.com/llir/llvm/ir/value"
)

type UnnamedValue interface {
	value.Named
	// IsUnnamed reports whether the local identifier is unnamed.
	IsUnnamed() bool
}

func main() {
	m, err := asm.ParseString("<string>", `declare void @foo()

declare i8* @bar()

define i8 @run() {
; <label>:0
  %1 = add i8 1, 2
  call void @foo()
  %2 = add i8 %1, 3
  ret i8 %2
}
`)

	if err != nil {
		panic(err)
	}

	nameToFunc := map[string]*ir.Func{}
	for _, f := range m.Funcs {
		nameToFunc[f.Name()] = f
	}

	for _, f := range m.Funcs {
		for _, b := range f.Blocks {
			for _, i := range b.Insts {
				if i, ok := i.(*ir.InstCall); ok {
					i.Callee = nameToFunc["bar"]
					// Force update type of i.
					i.Typ = nil
					i.Type()
				}
			}
		}
	}

	// Reset local variable IDs.
	for _, f := range m.Funcs {
		for _, b := range f.Blocks {
			for _, i := range b.Insts {
				if i, ok := i.(UnnamedValue); ok {
					if i.IsUnnamed() {
						// clear local ID.
						i.SetName("")
					}
				}
			}
		}
	}

	os.Stdout.WriteString(m.String())
}
```

**Comment by pwaller** [comment]
Would it be reasonable to have a `ResetNames()` function, and refer to that in the error message, for discoverability? I know there is always the question of where it should live.

**Comment by mewmew** [comment]
> Would it be reasonable to have a ResetNames() function, and refer to that in the error message, for discoverability? I know there is always the question of where it should live.

If so, I would put it in an `irutil` package, simply because it is functionality that is not *core* to the IR. If we put that method on `*ir.Func`, we would start to accumulate other *useful* methods quite quickly. I don't want `llir/llvm/ir` to end up as bloated an API as the official LLVM.

**Comment by mewmew** [comment]
Now that we have a solution to this, I'll go ahead and close. If you think we need to document this somewhere, in particular in relation to the "caching" of types, the just let me know. That behaviour is arguably non-intuitive, and thus deserves documentation. Just not sure *where* to put it.
