### ISSUE TITLE
Makefiles don't run, docs to generate from grammar etc?

### ISSUE THREAD

**Issue by pwaller** [llir/llvm#81]
I tried to run the Makefiles to generate code from grammar but found that they depend on a GOPATH with a `:` in them?

I suppose it would be good to update the Makefiles so that they don't depend on GOPATH.

My suggestion would be to use `go get` to install any needed programs into a `.gitignored` directory, and exec them from there, so that the result doesn't depend on what you happen to have in the PATH.

We could also make these `go get` invocations work from a separate `go.mod` so that the dependencies needed for the generators don't contaminate the transitive dependencies of llir/llvm.

Finally, it would be useful to document briefly how the generation process works, and/or give a single entry point in a top level Makefile. It isn't clear to me precisely what I need to do in which repositories to get everything uptodate, even after briefly looking into it. I've tried to add a new calling convention I'm experimenting with but found that the parser still doesn't recognize it. I don't yet trust that I have managed to run everything I need to run for everything to be uptodate.

**Comment by mewmew** [comment]
> I tried to run the Makefiles to generate code from grammar but found that they depend on a GOPATH with a : in them?

Most definitely. This was an oversight on my part. I thought I had tried to use GOPATHs also with only one path element, however, it seems that was not the case. My GOPATH contains colon two path elements.

> I suppose it would be good to update the Makefiles so that they don't depend on GOPATH.

I would agree, this makes sense. Especially since GOPATH is going away soon?

> My suggestion would be to use go get to install any needed programs into a .gitignored directory, and exec them from there, so that the result doesn't depend on what you happen to have in the PATH.

Sounds good to me. How about a `tools` directory?

> We could also make these go get invocations work from a separate go.mod so that the dependencies needed for the generators don't contaminate the transitive dependencies of llir/llvm.

Also sounds reasonable, we can add a `go.mod` to the tools directory then.

> Finally, it would be useful to document briefly how the generation process works, and/or give a single entry point in a top level Makefile. It isn't clear to me precisely what I need to do in which repositories to get everything uptodate, even after briefly looking into it. I've tried to add a new calling convention I'm experimenting with but found that the parser still doesn't recognize it. I don't yet trust that I have managed to run everything I need to run for everything to be uptodate.

Point taken. I'll plot up a rough overview description of the projects various components and how to get running with hacking various parts of the project; I'll add it the a `HACKING.md` file in llir/llvm.

**Comment by mewmew** [comment]
The Makefile of [llir/ll](https://github.com/llir/ll) has now been updated, and the Textmapper tool is now included as a Git submodule in a tools directory, rather than relying on it's presence in PATH or GOPATH.

The readme has also been updated to include an [Installation section](https://github.com/llir/ll#installation). @pwaller, could you verify that these steps work on your machine and that you are able to install the project and it's required tools using those steps?

**Comment by mewmew** [comment]
> Point taken. I'll plot up a rough overview description of the projects various components and how to get running with hacking various parts of the project; I'll add it the a HACKING.md file in llir/llvm.

As of commit cba2802ff1edaa1194183618982f56afd5506664 we have a rough outline of a HACKING.md document. We can extend it and refine different parts as we see fit. Let me know if there are other parts you would like to see extended upon.

@pwaller Also, I wrote this, mostly to get your thoughts on the matter:

> We should probably create an associated DESIGN.md document
to provide high-level motivation for various design decisions
and API choises. It could also be good to start defining the
projects goals and non-goals.

Cheers,
Robin

**Comment by pwaller** [comment]
Hey, this is all fantastic, thanks for that.

+1 to the DESIGN doc, I was thinking along the same lines before you suggested it.

I'm trying things out, will let you know how I get along if/when I succeed.

**Comment by pwaller** [comment]
This section feels like it is missing a make directive for `llvm/asm/enum/Makefile` ? https://github.com/llir/llvm/blob/fe7863fc401b878a96481975b4b4f74bf321514a/HACKING.md#llirllvm

**Comment by mewmew** [comment]
> This section feels like it is missing a make directive for llvm/asm/enum/Makefile ? https://github.com/llir/llvm/blob/fe7863fc401b878a96481975b4b4f74bf321514a/HACKING.md#llirllvm

I guess you are right. I thought you'd only re-generate the `asm/enum` package when you make changes to `ir/enum`, but it should be described non-the-less.

**Comment by mewmew** [comment]
I tried running running the [Install instructions](https://github.com/llir/llvm/blob/master/HACKING.md#installation) outside of GOROOT today, and with your update to `string2enum` it worked without error. Thus, I think we may close this issue. Feel free to open a new one for other documentation changes and additions as you see appropriate. For instance, an issue dedicated to design decisions.
