### ISSUE TITLE
DILocation uses 0 to signify line/column value not present

### ISSUE THREAD

**Issue by justinclift** [llir/llvm#91]
When generating debug info lines, it turns out the ones which should look like this:

```
!12 = !DILocation(line: 0, scope: !5)
[stuff]
!24 = !DILocation(line: 0, scope: !13)
[stuff]
!32 = !DILocation(line: 0, scope: !27, inlinedAt: !30)
```

Are missing the line field:

```
!12 = !DILocation(scope: !5)
[stuff]
!24 = !DILocation(column: 13, scope: !13)
[stuff]
!32 = !DILocation(scope: !27, inlinedAt: !30)
```

Looking at the code which generates the lines, the problem is simple to see:
https://github.com/llir/llvm/blob/c5c443dc6bf6217b0b5619d4f242e373dc3c6977/ir/metadata/specialized_metadata.go#L1128

https://github.com/llir/llvm/blob/c5c443dc6bf6217b0b5619d4f242e373dc3c6977/ir/metadata/specialized_metadata.go#L1160-L1163

Two main possibilities for adjusting this spring to mind:

1. Use a different value (`-1`?) to indicate when the value isn't present
2. Add a new field (`LineValid bool`?) for the same thing

Using `-1` seems like it could go badly, as the default value is `0`.  So people would need to manually set it to `-1` when they don't need it.

The 2nd option seems better (to me) as `LineValid` would default to `false`, so no special care would need to be taken for it.

The only downside would be that both the boolean, and the value itself, would need changing for the instances it's needed.

There's probably a better approach, just not sure what that is atm. :wink:

Can generate a suitable PR to fix this, but not sure on the preferred direction to take yet.

**Comment by justinclift** [comment]
As a simple initial approach, this seems to work:

https://github.com/justinclift/llir-llvm/commit/43aefdaa292766a789a44e479c648a943e58a4e5

Haven't tried running test cases yet (something for later), so it could fail spectacularly . :wink:

**Comment by mewmew** [comment]
Hi @justinclift,

Thanks for the issue report! And sorry for the late reply. I've been out trekking in Mongolia and thus had no access to the Internet. Now I'm back in Ulaanbaatar :)

Regarding the issue you noted, could you please elaborate why `line: 0` is needed?

The reason we exclude `line` when it has a zero value is because source files are assumed to start at line 1, and since `line` is marked as optional in the official C++ implementation of LLVM (ref below).

From [lib/AsmParser/LLParser.cpp](https://github.com/llvm/llvm-project/blob/b72664fd21cc1e25cd8420eb37eae3a701976394/llvm/lib/AsmParser/LLParser.cpp#L4370):

```cpp
/// ParseDILocationFields:
///   ::= !DILocation(line: 43, column: 8, scope: !5, inlinedAt: !6,
///   isImplicitCode: true)
bool LLParser::ParseDILocation(MDNode *&Result, bool IsDistinct) {
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)                                    \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(column, ColumnField, );                                             \
  REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(inlinedAt, MDField, );                                              \
  OPTIONAL(isImplicitCode, MDBoolField, (false));
  PARSE_MD_FIELDS();
#undef VISIT_MD_FIELDS
```

Cheers,
Robin

**Comment by justinclift** [comment]
Yeah, I'm not sure it's actually needed. :wink:

It was just in the IR I was trying to replicate in my initial learning process, without really understanding if it was or wasn't needed.

That IR was itself being generated by TinyGo, which is also "in development", so it's entirely possible the 0 value lines are an oversight there for now too. :wink:

Lets close this for now.  If it does turn out they're needed for some purpose, we can look into it later again. :smile:

**Comment by mewmew** [comment]
Hi Justin,

Thanks! Glad you reported the issue, it's always good to have a background discussion for these kind of design choices (e.g. how to handle optional values). And like you mentioned, should this issue resurface in the future, we can simple re-open this issue and continue the discussion.

Cheers,
Robin
