### ISSUE TITLE
proposal: make module as io.WriterTo

### ISSUE THREAD

**Issue by dannypsnl** [llir/llvm#93]
For example:
```go
mod := ir.NewModule()
buf := make([]byte, 0)
n, err := mod.Read(buf)
```

I think it is better than write a big string into the file(which currently does) and can combine with `io` interface abstraction directly.

**Comment by pwaller** [comment]
Hi @dannypsnl, I think the abstraction needs to be `mod.WriteTo(w)`, rather than `mod.Read()`. Otherwise the `mod` has to maintain reader state, where as, when writing, you can write as many bytes as you like.

Note that you can turn a writer into a reader by using an `io.Pipe()`:

```
r, w := io.Pipe()
go func() {
  mod.WriteTo(w)
}()

buf := make([]byte, 0)
n, err := r.Read(buf)
```

**Comment by dannypsnl** [comment]
Oh! You are right, I didn't think it clear.

**Comment by mewmew** [comment]
@dannypsnl This seems like a quite reasonable proposal as it would help limit memory usage. I'd like for us to include it in the v0.3 release of llir/llvm.

Would you care to flesh out an initial PR for the `func (m *Module) WriteTo(w io.Writer) (n int64, err error)` method?

Cheers,
Robin

**Comment by mewmew** [comment]
This is now implemented. Thanks @dannypsnl!
