### ISSUE TITLE
ir.NewLoad with string array

### ISSUE THREAD

**Issue by helperShang** [llir/llvm#98]
llvm gen code
```
%8 = getelementptr inbounds [2 x i8*], [2 x i8*]* %2, i64 0, i64 %7
 %9 = load i8*, i8** %8, align 8
```
error info
```
%5 = getelementptr [2 x [1 x i8]*], [2 x [1 x i8]*]* %1, i32 0, i32 0
%6 = load [1 x i8]*, [1 x i8]** %5
```

**Comment by pwaller** [comment]
Hi @helperShang - I am unable to understand quickly from what you've posted what the issue is.

Please explicitly state what the problem is.

What are you trying to do? Do you get an error message? Can you provide a minimal reproducer?
